name: zv_transport_app
description: "Z&V Transport â€“ Angebot App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  url_launcher: ^6.3.0
  path_provider: ^2.1.5
  path: ^1.9.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

flutter_icons:
  android: true
  ios: false
  image_path: assets/images/logo.png
  min_sdk_android: 21
